### ISSUE TITLE
Fails with latest NodeCG

### ISSUE THREAD

**Issue by coolacid** [Lange/lange-notify#3]
Error: lange-notify's package.json lacks a "nodecg" property, and therefore cannot be parsed.

**Comment by Lange** [comment]
Hi @coolacid!

Yep, unfortunately I've not had time to port lange-notify to the newly released NodeCG 0.7.x. To use this bundle, you'll need to use NodeCG's [`legacy-0.6`](https://github.com/nodecg/nodecg/tree/legacy-0.6) branch.

I'll leave this issue open to perhaps encourage me to find the time to port this bundle to NodeCG 0.7.

**Comment by Lange** [comment]
Fixed by https://github.com/Lange/lange-notify/releases/tag/v1.0.0
