### ISSUE TITLE
NodeCG 0.9 compatibility ?

### ISSUE THREAD

**Issue by Djiit** [Lange/lange-notify#5]
Hi there, 

Do you plan to release a 0.9.x compatible version of this bundle ?

Thanks for your work ;)

**Comment by Lange** [comment]
Hi @Djiit,

At this time I have no plans to update this bundle to v0.9, simply because I'm pretty busy and it's hard to find the time. I'd accept a pull request for it though.

**Comment by Djiit** [comment]
I'll be glad to help. Is there any migration guide I could follow ? I saw http://nodecg.com/tutorial-migrating-0.8-to-0.9.html (the Routing part)

**Comment by Lange** [comment]
Yep, that's the migration guide

**Comment by Djiit** [comment]
Ok, I managed to get it working someway (bumping nodecg compat. version + applying migration guide advices) but still have some errors about object belonging to multiple Replicants. i'll get back to it this weekend.

**Comment by Lange** [comment]
Ah yeah that was a bugfix made in 0.9 semi-recently. All you need to do is
clone the objects in question such that each one is unique, via a package
such as https://www.npmjs.com/package/clone

**Comment by Djiit** [comment]
Thanks! It seems to be cloned by lfg-nucleus already, i'll try to investigate further later.

**Comment by Djiit** [comment]
Fixed in #6
